### ISSUE TITLE
Comments: Deleting a page does not remove the comments file associated with it

### ISSUE THREAD

**Issue by ikisler** [sbrl/Pepperminty-Wiki#144]
Steps:
1. Create a page
2. Add comments to it
3. Delete the page
4. Examine the file system
--> Page file is removed, but the comments file remains

Sorry, I keep finding bugs. xP

**Comment by sbrl** [comment]
Oooooh ouch! We'll have to fix that one. Thanks for testing it more thoroughly than I ever could! :smiley_cat:

**Comment by sbrl** [comment]
Fixed
