### ISSUE TITLE
Enhancement:  Admin should be able to delete comments

### ISSUE THREAD

**Issue by ikisler** [sbrl/Pepperminty-Wiki#145]
This would be excellent for moderation purposes.

Some things to think about related to this:
- Should deleting a parent comment delete all of its children?
- Should copies of deleted comments be kept, but hidden from normal users?
- Should users also have the power to delete their own comments?

**Comment by sbrl** [comment]
Good questions. Perhaps we could take an approach similar to reddit.

 - Deleting a comment hides it from all but moderators
 - Deleting a comment hides all child comments
 - Deleting a comment squashes all future notifications from the deleted comment and all it's children
 - Users should be able to both edit and delete their own comments.

**Comment by sbrl** [comment]
I've just thought of something else. If the comments are on a user's page or any subpages thereof, then they should have the power to delete comments on those pages. Same for deleting pages, come ot think about it.

**Comment by sbrl** [comment]
That's the deleting of comments implemented! Comments without replies are deleted altogether, and comments with replies are wiped but left in-place. More improvements are needed in this area though, I think.

**Comment by sbrl** [comment]
Closing, since this has been implemented. We might return our focus back to this aspect of Pepperminty Wiki at some point, but those efforts should be documented in a new issue.
