### ISSUE TITLE
Docker Release

### ISSUE THREAD

**Issue by sunjam** [sbrl/Pepperminty-Wiki#161]
Hi, I'm wondering if there is a docker version of this wiki available.

**Comment by sbrl** [comment]
Hey, @sunjam!

Hey! As I mentioned in the Gitter chat, there isn't a docker release available yet. It's certainly something we can work on! I don't have much experience with Docker yet. Can you help, or point me towards some documentation?

Also, what's the use-case for a Dockerised version, out of curiosity?

**Comment by SQL-enwiki** [comment]
Agreed with not sure about what the use-case here would be, but - done. See: https://cloud.docker.com/repository/registry-1.docker.io/sqlatenwiki/peppermintywiki

**Comment by sbrl** [comment]
Hey, thanks @SQL-enwiki! After creating a Docker Hub account, that link loaded for me. How do I see the source code for that though? I can't seem to find a link anywhere.

**Comment by SQL-enwiki** [comment]
> Hey, thanks @SQL-enwiki! After creating a Docker Hub account, that link loaded for me. How do I see the source code for that though? I can't seem to find a link anywhere.

Sure - here's the files I use, https://github.com/SQL-enwiki/peppermintydocker . I git clone peppermintywiki into ./webroot, and the update.sh script runs every day.

Most everything there is based on this guide: https://docs.docker.com/develop/develop-images/baseimages/

**Comment by sbrl** [comment]
Hey, awesome! Thanks for the hard work :-)

How do you suggest we make this the official Docker image? Shall I we put a link in the README?

**Comment by sbrl** [comment]
Just noticed that this pulls from master. Is there a way to use the latest release / tag?

Alternatively I can create a 'stable' branch that's always the latest release if need be. Need to look into some release automation there though.

**Comment by sunjam** [comment]
You could offer two docker options: _Stable_ and _Latest_

**Comment by sbrl** [comment]
Sounds good!

For the stable one we can do something like this: 

```bash
git checkout "$(git describe --abbrev=0 --tags)"
```

The only reason I bring it up is 'cause I occasionally leave `master` somewhat broken if I'm in the middle of something and don't have the time to finish it (currently working on interwiki links atm) :P

**Comment by SQL-enwiki** [comment]
I've got this sorted. There are two tags in the docker hub at the moment. One with the tag v0.17.1, and one tagged "master".

As more releases come out, it should auto-add the release version tag

**Comment by sbrl** [comment]
Awesome, thanks @SQL-enwiki :smiley_cat:

**Comment by sbrl** [comment]
I think we can safely close this issue for now.

Please open another one if there are any further issues :-)
