### ISSUE TITLE
build.sh Fails

### ISSUE THREAD

**Issue by lbonanomi** [sbrl/Pepperminty-Wiki#177]
Its a snippy little complaint, but [this line](https://github.com/sbrl/Pepperminty-Wiki/blob/05615b4c81712a29e87e014893fbc02fc8aaa615/build.sh#L12) of the build script is always going to fail on an initial clone. 

Example: 

```
# ./build.sh setup
./build.sh: line 28: ./lantern-build-engine/lantern.sh: No such file or directory
```

Would you consider testing as `[ ! -x "${lantern_path}/lantern.sh" ];` instead?

**Comment by sbrl** [comment]
Oh, my! Thanks for pointing that out. I've actually fixed that in other projects that use lantern. I'll fix it here too.

**Comment by sbrl** [comment]
Erm taking a look at it, I notice that I've already applied the fix: https://github.com/sbrl/Pepperminty-Wiki/blob/05615b4c81712a29e87e014893fbc02fc8aaa615/build.sh#L26

```
if [ ! -d "${lantern_path}" ]; then git submodule update --init "${lantern_path}"; fi
```

Are you using the latest version, @lbonanomi?

**Comment by lbonanomi** [comment]
@sbrl I'm working with a hot-off-the-press copy, but using a vanilla `git clone` which creates an empty dir for a submodule. Not sure if this is a better job for a code fix or a behavior change for the would-be user.

I'm overlooking a plain instruction in the README, aren't I?

**Comment by sbrl** [comment]
Ahhhh  I see. I'll fix that check right away then.

**Comment by sbrl** [comment]
Done :-)
