### ISSUE TITLE
build.sh looks for NPM twice

### ISSUE THREAD

**Issue by lbonanomi** [sbrl/Pepperminty-Wiki#178]
build.sh [looks for "npm" twice](https://github.com/sbrl/Pepperminty-Wiki/blob/05615b4c81712a29e87e014893fbc02fc8aaa615/build.sh#L57-L58), was this intended to check for PHP as-well?

If it was meant to check for PHP, could the check be either supplemented by or replaced with a test of `php -m | grep -q intl`? I'm working with the rh-php73 RPM right now, which doesn't install the intl extension by default and left me with a scary error message.

**Comment by sbrl** [comment]
Great catch - I suspect you're right. Note that the [documentation lists the PHP modules you need to have installed](https://starbeamrainbowlabs.com/labs/peppermint/__nightdocs/04-Getting-Started.html).

Note also that I've recently upgraded to PHP 7.4 in my development environment, and as a result I've squashed a number of issues generating warnings (and a crash!) when using PHP 7.4 just yesterday.

I'll look at adding that test for modules too :-)

**Comment by sbrl** [comment]
Fixed! :D
