### ISSUE TITLE
latest tag missing in Docker

### ISSUE THREAD

**Issue by sunjam** [sbrl/Pepperminty-Wiki#189]
`docker pull sqlatenwiki/peppermintywiki`
Using default tag: latest
Error response from daemon: manifest for sqlatenwiki/peppermintywiki:latest not found: manifest unknown: manifest unknown

Seems a latest tag has not been defined, but I see [there are other tags available](https://hub.docker.com/r/sqlatenwiki/peppermintywiki/tags).

**Comment by sbrl** [comment]
Hey there, @sunjam! I hadn't actually noticed that - thanks for pointing it out!

I'm not actually the maintainer of the Docker image. That's graciously provided by @SQL-enwiki if I recall correctly.

@SQL-enwiki, would you be able to help out here?

**Comment by SQL-enwiki** [comment]
If I understand correctly, latest == dev as far as tags go. Should be pretty easy to alias.

**Comment by SQL-enwiki** [comment]
In any case, latest now exists, and is the same as stable.

**Comment by sunjam** [comment]
Awesome, `$ docker pull sqlatenwiki/peppermintywiki` succeeds
