### ISSUE TITLE
Creating a new page results in the recreation of the Main Page.

### ISSUE THREAD

**Issue by virtadpt** [sbrl/Pepperminty-Wiki#217]
When using the new page creation feature (`action=edit&unknownpagename=yes`), the Main Page of my wiki is always overwritten with whatever stuff I want to put into the main page.  So, whenever I log in, rather than getting my "redirecting to index page" action I get "Main Page" and whatever I just put into the new page.

**Comment by sbrl** [comment]
Fixed! The page editor was submitting the page name as a `POST` parameter, but Pepperminty Wiki expected it as a GET.

Pepperminty Wiki now supports setting `page` as either GET or POST now (GET takes priority over POST).
