### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by letyphon** [sbrl/Pepperminty-Wiki#218]
Hello,
My messages on reddit are "failed to send", so ı decided to ask you my issue here. First, thank you very much for your kindness and taking your time to reply me.

My issue is that, php and all required modules are installed on my pc (Ubuntu), I put the index.php file in to the /var/www/html directory and go to the web browser, then what I see is a blank page. I have another wiki under the same directory (W2wiki), it works perfectly but I could not make pepperminty wiki work. What could be the issue?

**Comment by sbrl** [comment]
Hey there! Thanks for opening an issue here (it's much easier to converse here than on Reddit :slightly_smiling_face:).

Sounds like a configuration issue. Have you checked your server logs? You should be able to find them somewhere in `/var/log`. For example, if you use Nginx they should be in `/var/log/nginx`.

**Comment by sbrl** [comment]
Any update, @letyphon?

**Comment by sbrl** [comment]
Ok, I'm going to close this issue for now, but if you reply I'll re-open and we can continue the discussion.
