### ISSUE TITLE
Horizontal scrollbar on docs mainpage

### ISSUE THREAD

**Issue by Epictek** [sbrl/Pepperminty-Wiki#225]
Horizontal overflow on the documentation homepage.

I'm assuming it has something to do with the screenshot animation at the top of the page.

Browser Firefox, windows 11.

https://media.discordapp.net/attachments/364434318413660161/883139156933496852/unknown.png

**Comment by sbrl** [comment]
Thanks! I'll take a look.

**Comment by sbrl** [comment]
I think I've fixed it!

Thanks for reporting. Going to close this now, but if this isn't fixed comment again and I'll take reopen.
