### ISSUE TITLE
IIS Setup Instructions/config

### ISSUE THREAD

**Issue by npnance** [sbrl/Pepperminty-Wiki#228]
Hello-

I was able to install Pepperminty locally on my Win 10 machine with IIS. If you'd like to add this to the setup instructions, please do.

---

For those running IIS, the following will grant the appropriate read and write permissions to the IIS_IUSRS group, and prevent the peppermint.json file from being retrieved. 

Open an elevated (administrator) Command Prompt and run the following. 
Change the "installdir" variable to the directory where you've placed the Pepperminty index.php file.
This assumes your IIS website is named "Default Web Site" and that you want to create a "pepperminty" application under it. If yours is different, change the variables appropriately.

```
SETLOCAL
SET installdir=c:\inetpub\wwwroot\pepperminty\
SET iissitename="Default Web Site"
SET iisappfull="Default Web Site/pepperminty"
SET iisapppath="/pepperminty"

cd /d %WINDIR%\system32\inetsrv\
appcmd add app /site.name:%iissitename% /path:%iisapppath% /physicalPath:%installdir%
appcmd set config %iisappfull% -section:system.webServer/security/requestFiltering /+"hiddenSegments.[segment='peppermint.json']"
cd /d %installdir%
icacls . /grant IIS_IUSRS:(OI)(CI)RXWM
ENDLOCAL
```

Thanks.

**Comment by sbrl** [comment]
Hey there! Thanks for the instructions here! Unfortunately, I do not have a Windows machine to verify these functions, but I trust your instructions here! Have you considered opening a pull request? You'll probably want to make an edit to the docs here: https://github.com/sbrl/Pepperminty-Wiki/blob/master/docs/04-Getting-Started.md#setup-instructions

They are all in Markdown, so no fancy HTML/CSS/JS editing necessary :-)

**Comment by npnance** [comment]
Will do.
