### ISSUE TITLE
Preview changes

### ISSUE THREAD

**Issue by sbrl** [sbrl/Pepperminty-Wiki#59]
It would make Pepperminty Wiki much more useable if you could preview changes before you made them.

**Comment by sbrl** [comment]
Umm upon further investigation, it looks like this might be much more involved than I first thought. This may not make it into 0.11.

**Comment by sbrl** [comment]
Nope, this isn't looking likely for 0.13 either. I should probably take another look at implementing this.

**Comment by ikisler** [comment]
I'm interested in working on this feature.  How should the UI function, though?  I was thinking there'd be a Preview button next to the Save button, which then either reloads the page with the preview above and edit area below, or it would open a new tab/window with the preview.

What do you think?  Any better options?

**Comment by sbrl** [comment]
@ikisler Cool! That would be very helpful if you would like to work on it :smiley_cat:

Yeah, a preview button next to the save button would be great. While I like the idea of it opening in a new page, I think it would be less confusing to have it reload the page and display the preview above :smiley:

I'd recommend adding a new `page-preview` or `preview-page` action for this. I can think of 2 approaches for integrating the functionality:

 - Putting the `page-preview` action in `page-edit`, and adding the preview button to the html form
 - Putting the `page-preview` action in a new module called `feature-preview` or something, and adding a conditional addition to the HTML in `page-edit` based on `module_exists` or even `has_action`

The source of Pepperminty Wiki is a bit odd, but that's just because it's been around for a while and I'd like to keep everything inside a single file - at least the initial one you copy to your web server (I know I've cheated a bit with the new parser.... :P). If you need any help, just ask! :smiley: 

Let me know how you get on!

**Comment by sbrl** [comment]
This has been implemented :smiley_cat:
