### ISSUE TITLE
datalist tag

### ISSUE THREAD

**Issue by nibreh** [sbrl/Pepperminty-Wiki#8]
Hello

There is a tag `</datalist>` alone

look this picture
![capture du 2015-06-15 11 15 36](https://cloud.githubusercontent.com/assets/7314006/8156794/ecf05916-134f-11e5-98f3-ed22305ec2e2.png)

cheers

**Comment by sbrl** [comment]
Good spot!

It must be left over from a rewrite. I will fix that now.

**Comment by sbrl** [comment]
Looks like I forgot to append to the string when creating the `<datalist/>` tag that powers the search box.
All fixed! :)
